# Using NumPy Arrays

In [2]:
import csv as csv
import numpy as np

csv_file_object = csv.reader(open('./train.csv', 'rb')) 
header = csv_file_object.next() 
data=[] 

for row in csv_file_object:
    data.append(row)
data = np.array(data) 

In [3]:
print data

[['1' '0' '3' ..., '7.25' '' 'S']
 ['2' '1' '1' ..., '71.2833' 'C85' 'C']
 ['3' '1' '3' ..., '7.925' '' 'S']
 ..., 
 ['889' '0' '3' ..., '23.45' '' 'S']
 ['890' '1' '1' ..., '30' 'C148' 'C']
 ['891' '0' '3' ..., '7.75' '' 'Q']]


In [ ]:
data[0:15, 5]

In [ ]:
type(data[0::,5]) 

In [ ]:
ages_onboard = data[0::,5].astype(np.float) 

# Pandas

## Setting up the Data Frame

In [1]:
import pandas as pd
import numpy as np

# For .read_csv, always use header=0 when you know row 0 is the header row
df = pd.read_csv('train.csv', header=0)

In [ ]:
df

In [ ]:
df.head(3)

In [ ]:
df.tail(5)

In [ ]:
type(df)

In [ ]:
df.dtypes

In [ ]:
df.info()

In [ ]:
df.describe()

## Referencing and Filtering

In [ ]:
df['Age'][0:10]

In [ ]:
df.Age[0:10]

In [ ]:
df.Cabin[0:10]

In [ ]:
type(df['Age'])

In [ ]:
df.Age.mean()

In [ ]:
df.Age.median()

In [ ]:
df[['Sex', 'Pclass', 'Age']]

In [ ]:
df[df['Age'] > 60]

In [ ]:
df[df['Age'] > 60][['Sex', 'Pclass', 'Age']]

In [ ]:
df[df['Age'].isnull()][['Sex', 'Pclass', 'Age']]

In [ ]:
for i in range(1,4):
    print i, len(df[(df['Sex'] == "male") & (df['Pclass'] == i)])

In [ ]:
df[(df['Sex'] == "male") & (df['Pclass'] == 2)]

In [ ]:
import pylab as P
df['Age'].hist()
P.show()

In [ ]:
df['Gender'] = 4
df['Gender'] = df['Sex'].map( lambda x: x[0].upper() )

In [ ]:
df.Gender

In [4]:
df['Gender'] = df['Sex'].map( {'female': 0, 'male': 1} ).astype(int)

In [ ]:
df.Gender

In [ ]:
df['Gender']

In [5]:
df.Embarked.unique()

array(['S', 'C', 'Q', nan], dtype=object)

In [6]:
df['EmbarkedCode'] = df['Embarked'].map( {'S': 0, 'C': 1, 'Q': 2, np.nan: 3} ).astype(int)

In [ ]:
df.EmbarkedCode

In [7]:
median_ages = np.zeros((2,3));
for i in range(0, 2):
    for j in range(0, 3):
        median_ages[i,j] = df[(df['Gender'] == i) & \
                              (df['Pclass'] == j+1)]['Age'].dropna().median();
 
median_ages

array([[ 35. ,  28. ,  21.5],
       [ 40. ,  30. ,  25. ]])

In [8]:
df['AgeFill'] = df['Age']
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  Gender  EmbarkedCode  \
0      0         A/5 21171   7.2500   NaN        S       1             0   
1      0          PC 17599  71.2833   C85        C       0             1   
2      0  STON/O2. 3101282   7.9250   NaN        S       0             0   
3      0            113803  53.1000  C123        S       0             0   
4      0            373450   8.0500   NaN        S       1             0   

   AgeFill  
0     22.0  
1     38.0  
2     26.0  
3     35.0  
4     35.0

In [9]:
df[ df['Age'].isnull() ][['Gender','Pclass','Age','AgeFill']].head(10)

Gender  Pclass  Age  AgeFill
5        1       3  NaN      NaN
17       1       2  NaN      NaN
19       0       3  NaN      NaN
26       1       3  NaN      NaN
28       0       3  NaN      NaN
29       1       3  NaN      NaN
31       0       1  NaN      NaN
32       0       3  NaN      NaN
36       1       3  NaN      NaN
42       1       3  NaN      NaN

In [10]:
for i in range(0, 2):
    for j in range(0, 3):
        df.loc[ (df.Age.isnull()) & (df.Gender == i) & (df.Pclass == j+1),\
                'AgeFill'] = median_ages[i,j];

In [11]:
df[ df['Age'].isnull() ][['Gender','Pclass','Age','AgeFill']].head(10)

Gender  Pclass  Age  AgeFill
5        1       3  NaN     25.0
17       1       2  NaN     30.0
19       0       3  NaN     21.5
26       1       3  NaN     25.0
28       0       3  NaN     21.5
29       1       3  NaN     25.0
31       0       1  NaN     35.0
32       0       3  NaN     21.5
36       1       3  NaN     25.0
42       1       3  NaN     25.0

In [ ]:
df['AgeIsNull'] = pd.isnull(df.Age).astype(int)

In [ ]:
df.describe()

# Feature Engineering

In [12]:
df['FamilySize'] = df['SibSp'] + df['Parch']
df['Age*Class'] = df.AgeFill * df.Pclass

In [13]:
df.describe()

C:\Users\Cathy\Anaconda2\lib\site-packages\numpy\lib\function_base.py:3834: RuntimeWarning: Invalid value encountered in percentile
  RuntimeWarning)


PassengerId    Survived      Pclass         Age       SibSp  \
count   891.000000  891.000000  891.000000  714.000000  891.000000   
mean    446.000000    0.383838    2.308642   29.699118    0.523008   
std     257.353842    0.486592    0.836071   14.526497    1.102743   
min       1.000000    0.000000    1.000000    0.420000    0.000000   
25%     223.500000    0.000000    2.000000         NaN    0.000000   
50%     446.000000    0.000000    3.000000         NaN    0.000000   
75%     668.500000    1.000000    3.000000         NaN    1.000000   
max     891.000000    1.000000    3.000000   80.000000    8.000000   

            Parch        Fare      Gender  EmbarkedCode     AgeFill  \
count  891.000000  891.000000  891.000000    891.000000  891.000000   
mean     0.381594   32.204208    0.647587      0.368126   29.112424   
std      0.806057   49.693429    0.477989      0.647602   13.304424   
min      0.000000    0.000000    0.000000      0.000000    0.420000   
25%      0.000000    7.910400    0.000000      0.000000   21.500000   
50%      0.000000   14.454200    1.000000      0.000000   26.000000   
75%      0.000000   31.000000    1.000000      1.000000   36.000000   
max      6.000000  512.329200    1.000000      3.000000   80.000000   

       FamilySize   Age*Class  
count  891.000000  891.000000  
mean     0.904602   62.614860  
std      1.613459   31.362024  
min      0.000000    0.920000  
25%      0.000000   40.000000  
50%      0.000000   63.000000  
75%      1.000000   75.000000  
max     10.000000  222.000000

In [14]:
df.dtypes[df.dtypes.map(lambda x: x=='object')]

Name        object
Sex         object
Ticket      object
Cabin       object
Embarked    object
dtype: object

In [15]:
df = df.drop(['Name', 'Sex', 'Ticket', 'Cabin', 'Embarked'], axis=1) 
df = df.drop(['Age'], axis=1)
df = df.drop(['PassengerId'], axis=1)
df = df.dropna()

In [16]:
df.describe()

Survived      Pclass       SibSp       Parch        Fare      Gender  \
count  891.000000  891.000000  891.000000  891.000000  891.000000  891.000000   
mean     0.383838    2.308642    0.523008    0.381594   32.204208    0.647587   
std      0.486592    0.836071    1.102743    0.806057   49.693429    0.477989   
min      0.000000    1.000000    0.000000    0.000000    0.000000    0.000000   
25%      0.000000    2.000000    0.000000    0.000000    7.910400    0.000000   
50%      0.000000    3.000000    0.000000    0.000000   14.454200    1.000000   
75%      1.000000    3.000000    1.000000    0.000000   31.000000    1.000000   
max      1.000000    3.000000    8.000000    6.000000  512.329200    1.000000   

       EmbarkedCode     AgeFill  FamilySize   Age*Class  
count    891.000000  891.000000  891.000000  891.000000  
mean       0.368126   29.112424    0.904602   62.614860  
std        0.647602   13.304424    1.613459   31.362024  
min        0.000000    0.420000    0.000000    0.920000  
25%        0.000000   21.500000    0.000000   40.000000  
50%        0.000000   26.000000    0.000000   63.000000  
75%        1.000000   36.000000    1.000000   75.000000  
max        3.000000   80.000000   10.000000  222.000000

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 891 entries, 0 to 890
Data columns (total 10 columns):
Survived        891 non-null int64
Pclass          891 non-null int64
SibSp           891 non-null int64
Parch           891 non-null int64
Fare            891 non-null float64
Gender          891 non-null int32
EmbarkedCode    891 non-null int32
AgeFill         891 non-null float64
FamilySize      891 non-null int64
Age*Class       891 non-null float64
dtypes: float64(3), int32(2), int64(5)
memory usage: 69.6 KB


In [41]:
train_data = df.values
train_data

array([[  0. ,   3. ,   1. , ...,  22. ,   1. ,  66. ],
       [  1. ,   1. ,   1. , ...,  38. ,   1. ,  38. ],
       [  1. ,   3. ,   0. , ...,  26. ,   0. ,  78. ],
       ..., 
       [  0. ,   3. ,   1. , ...,  21.5,   3. ,  64.5],
       [  1. ,   1. ,   0. , ...,  26. ,   0. ,  26. ],
       [  0. ,   3. ,   0. , ...,  32. ,   0. ,  96. ]])

In [20]:
data

array([['1', '0', '3', ..., '7.25', '', 'S'],
       ['2', '1', '1', ..., '71.2833', 'C85', 'C'],
       ['3', '1', '3', ..., '7.925', '', 'S'],
       ..., 
       ['889', '0', '3', ..., '23.45', '', 'S'],
       ['890', '1', '1', ..., '30', 'C148', 'C'],
       ['891', '0', '3', ..., '7.75', '', 'Q']], 
      dtype='|S82')

# Random Forests

In [50]:
test_df = pd.read_csv('test.csv', header=0)
test_df['Gender'] = test_df['Sex'].map( {'female': 0, 'male': 1} ).astype(int)
for i in range(0, 2):
    for j in range(0, 3):
        test_df.loc[ (test_df.Age.isnull()) & (test_df.Gender == i) & (test_df.Pclass == j+1),\
                'AgeFill'] = median_ages[i,j];
test_df['EmbarkedCode'] = test_df['Embarked'].map( {'S': 0, 'C': 1, 'Q': 2, np.nan: 3} ).astype(int)
test_df['FamilySize'] = test_df['SibSp'] + test_df['Parch']
test_df['Age*Class'] = test_df.AgeFill * test_df.Pclass
test_df = test_df.drop(['Name', 'Sex', 'Ticket', 'Cabin', 'Embarked', 'Age', 'PassengerId'], axis=1) 
test_df = test_df.dropna()
test_df

Pclass  SibSp  Parch     Fare  Gender  AgeFill  EmbarkedCode  FamilySize  \
10        3      0      0   7.8958       1     25.0             0           0   
22        1      0      0  31.6833       0     35.0             0           0   
29        3      2      0  21.6792       1     25.0             1           2   
33        3      1      2  23.4500       0     21.5             0           3   
36        3      0      0   8.0500       0     21.5             0           0   
39        3      0      0  56.4958       1     25.0             0           0   
41        1      0      0  26.5500       1     40.0             0           0   
47        3      0      0   7.7500       1     25.0             2           0   
54        2      0      0  15.5792       1     30.0             1           0   
58        3      1      0  16.1000       1     25.0             0           1   
65        2      0      0  21.0000       0     28.0             0           0   
76        3      0      0   8.0500       1     25.0             0           0   
83        3      0      0   7.8958       1     25.0             0           0   
84        2      0      0  10.7083       1     30.0             2           0   
85        3      1      0  14.4542       1     25.0             1           1   
88        3      0      0   7.7500       0     21.5             2           0   
91        3      0      0   7.7750       1     25.0             0           0   
93        3      0      0   8.0500       1     25.0             0           0   
102       3      0      0   7.7500       1     25.0             2           0   
107       3      0      0   7.7500       1     25.0             2           0   
108       3      0      0   8.7125       1     25.0             0           0   
111       3      0      0   7.7792       0     21.5             2           0   
116       3      0      0   6.4375       1     25.0             1           0   
121       3      1      0   7.7500       1     25.0             2           1   
124       3      0      0   7.7500       1     25.0             2           0   
127       3      2      0  23.2500       0     21.5             2           2   
132       3      0      4  25.4667       0     21.5             0           4   
133       3      1      0   6.4375       1     25.0             1           1   
146       1      0      0  51.8625       1     40.0             0           0   
148       1      0      0  26.5500       1     40.0             0           0   
..      ...    ...    ...      ...     ...      ...           ...         ...   
268       3      0      0   8.0500       0     21.5             0           0   
271       3      0      0   7.7500       1     25.0             2           0   
273       3      1      0  15.5000       0     21.5             2           1   
274       3      0      0   7.2250       1     25.0             1           0   
282       3      0      0   7.7500       0     21.5             2           0   
286       3      0      0   7.2500       1     25.0             0           0   
288       3      0      0   7.2292       1     25.0             1           0   
289       3      0      0   8.0500       1     25.0             0           0   
290       1      0      0  39.6000       1     40.0             0           0   
292       3      0      0   7.2292       1     25.0             1           0   
297       3      2      0  21.6792       1     25.0             1           2   
301       2      0      0  15.0458       1     30.0             1           0   
304       3      0      0   7.7500       0     21.5             2           0   
312       3      0      0   7.5750       1     25.0             0           0   
332       3      0      0   7.2250       1     25.0             1           0   
339       3      0      0   7.2292       1     25.0             1           0   
342       3      1      9  69.5500       1     25.0             0          10   
344       3      1      1  14.5000  

In [51]:
test_data = test_df.values
test_data

array([[  3.    ,   0.    ,   0.    ,   7.8958,   1.    ,  25.    ,
          0.    ,   0.    ,  75.    ],
       [  1.    ,   0.    ,   0.    ,  31.6833,   0.    ,  35.    ,
          0.    ,   0.    ,  35.    ],
       [  3.    ,   2.    ,   0.    ,  21.6792,   1.    ,  25.    ,
          1.    ,   2.    ,  75.    ],
       [  3.    ,   1.    ,   2.    ,  23.45  ,   0.    ,  21.5   ,
          0.    ,   3.    ,  64.5   ],
       [  3.    ,   0.    ,   0.    ,   8.05  ,   0.    ,  21.5   ,
          0.    ,   0.    ,  64.5   ],
       [  3.    ,   0.    ,   0.    ,  56.4958,   1.    ,  25.    ,
          0.    ,   0.    ,  75.    ],
       [  1.    ,   0.    ,   0.    ,  26.55  ,   1.    ,  40.    ,
          0.    ,   0.    ,  40.    ],
       [  3.    ,   0.    ,   0.    ,   7.75  ,   1.    ,  25.    ,
          2.    ,   0.    ,  75.    ],
       [  2.    ,   0.    ,   0.    ,  15.5792,   1.    ,  30.    ,
          1.    ,   0.    ,  60.    ],
       [  3.    ,   1.    ,   0.    ,

In [52]:
# Import the random forest package
from sklearn.ensemble import RandomForestClassifier 

# Create the random forest object which will include all the parameters
# for the fit
forest = RandomForestClassifier(n_estimators = 100)

# Fit the training data to the Survived labels and create the decision trees
forest = forest.fit(train_data[0::,1::],train_data[0::,0])

# Take the same decision trees and run it on the test data
output = forest.predict(test_data)

In [53]:
output

array([ 0.,  1.,  1.,  0.,  1.,  1.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,
        0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  1.,
        0.,  0.,  0.,  0.,  0.,  1.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,
        0.,  1.,  0.,  0.,  1.,  0.,  0.,  1.,  0.,  0.,  0.,  1.,  0.,
        0.,  0.,  0.,  0.,  1.,  0.,  1.,  0.,  1.,  0.,  0.,  0.,  0.,
        0.,  1.,  0.,  1.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  1.,  1.,  0.,  0.,  1.])